// ------

const search_card_products = [
  {
    id: 0,
    img: "images/result-img15.png",
    name: "599,99 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 3.5,
    isLiked: false,
  },
  {
    id: 1,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 2,
    img: "images/result-img3.png",
    name: "159,99 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 3,
    img: "images/result-img2.png",
    name: "49.39 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },
  {
    id: 4,
    img: "images/result-img14.png",
    name: "77,99 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 2,
    isLiked: false,
  },
  {
    id: 5,
    img: "images/result-img3.png",
    name: "159,99 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 6,
    img: "images/result-img15.png",
    name: "599,99 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 7,
    img: "images/result-img2.png",
    name: "49,39 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },
  {
    id: 8,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 2,
    isLiked: false,
  },
  {
    id: 9,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 10,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 11,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },

  {
    id: 13,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 14,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 4.5,
    isLiked: false,
  },
  {
    id: 15,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 3.5,
    isLiked: false,
  },
  {
    id: 16,
    img: "images/result-img15.png",
    name: "599,99 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 3.5,
    isLiked: false,
  },
  {
    id: 17,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 18,
    img: "images/result-img3.png",
    name: "159,99 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 19,
    img: "images/result-img2.png",
    name: "49.39 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },
  {
    id: 20,
    img: "images/result-img14.png",
    name: "77,99 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 2,
    isLiked: false,
  },
  {
    id: 21,
    img: "images/result-img3.png",
    name: "159,99 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 22,
    img: "images/result-img15.png",
    name: "599,99 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 23,
    img: "images/result-img2.png",
    name: "49,39 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },
  {
    id: 24,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 2,
    isLiked: false,
  },
  {
    id: 25,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 26,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 5,
    isLiked: false,
  },
  {
    id: 27,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 4,
    isLiked: false,
  },

  {
    id: 29,
    img: "images/result-img2.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    rating: 3,
    isLiked: false,
  },
  {
    id: 30,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    rating: 4.5,
    isLiked: false,
  },
  {
    id: 15,
    img: "images/result-img3.png",
    name: "44.50 ₽",
    name_price: "50.50 ₽",
    desc: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    rating: 3.5,
    isLiked: false,
  },
];

const massiv2 = [
  {
    id: 0,
    img: "images/result-img22.png",
    name: "599,99 ₽",
    name_price: "И получайте бонусы при покупке в магазинах и на сайте",
    desc: "Оформите карту «Северяночка» ",
    rating: 3.5,
    isLiked: false,
  },
  {
    id: 1,
    img: "images/result-img23.png",
    name: "44.50 ₽",
    name_price: "И получайте вдвое больше бонусов",
    desc: "Покупайте акционные товары",
    rating: 3,
    isLiked: false,
  },
];

const massiv33 = [
  {
    id: 0,
    img: "images/result-img25.png",
    name: "599,99 ₽",
    name_price: "Режим использования масок и перчаток на территории магазинов",
    desc: "Подробная информация о режимах использования масок и перчаток на территории магазинов ЛЕНТА. Информация обновляется каждый будний день.",
    rating: 3.5,
    isLiked: false,
  },
  {
    id: 1,
    img: "images/status-img26.png",
    name: "44.50 ₽",
    name_price: "Весеннее настроение для каждой",
    desc: "8 Марта – это не просто Международный женский день, это ещё день тюльпанов, приятных сюрпризов и праздничных тёплых пожеланий taviling milk a foote deleta man spoon",
    rating: 3,
    isLiked: false,
  },
  {
    id: 3,
    img: "images/result-img27.png",
    name: "599,99 ₽",
    name_price: "ЗОЖ или ФАСТФУД. А вы на чьей стороне? Голосуем!",
    desc: "Голосуйте за любимые категории, выбирайте категорию-победителя в мобильном приложении и получайте кешбэк 10% баллами в апреле!",
    rating: 3.5,
    isLiked: false,
  },
];

const massiv34 = [
  {
    id: 0,
    img: "images/catigori1.png",
    name: "Молоко, сыр, яйцо",
  },
  {
    id: 3,
    img: "images/catigori2.png",
    name: "Хлеб",
  },
  {
    id: 3,
    img: "images/catigori3.png",
    name: "Фрукты и овощи",
  },
  {
    id: 3,
    img: "images/catigori4.png",
    name: "Напитки",
  },
  {
    id: 3,
    img: "images/catigori3.png",
    name: "Кондитерские изделия",
  },
  {
    id: 3,
    img: "images/catigori6.png",
    name: "Чай, кофе",
  },

  {
    id: 3,
    img: "images/catigori7.png",
    name: "Бакалея",
  },
  {
    id: 3,
    img: "images/catigori8.png",
    name: "Здоровое питание",
  },
  {
    id: 3,
    img: "images/catigori9.png",
    name: "Зоотовары",
  },
  {
    id: 3,
    img: "images/catigori3.png",
    name: "Фрукты и овощи",
  },
  {
    id: 3,
    img: "images/catigori4.png",
    name: "Напитки",
  },
  {
    id: 3,
    img: "images/catigori3.png",
    name: "Кондитерские изделия",
  },
  {
    id: 3,
    img: "images/catigori6.png",
    name: "Чай, кофе",
  },

  {
    id: 3,
    img: "images/catigori7.png",
    name: "Бакалея",
  },
  {
    id: 3,
    img: "images/catigori8.png",
    name: "Здоровое питание",
  },
  {
    id: 3,
    img: "images/catigori9.png",
    name: "Зоотовары",
  },
];
